name: andrewwhaley
favicon: null
layout_spectrum: 0.28015492926351726
typography_spectrum: 0.14262741059064865
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ccdadb'
    - '#a1b6c1'
    - '#181a18'
    - '#6e99ad'
    - '#ac9971'
  brandStrength: 0.6875
  lightness: 0.6875
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
