name: andrewwhaley
favicon: null
layout_spectrum: 0.28015492926351726
typography_spectrum: 0.14262741059064865
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#969291'
    - '#17252e'
    - '#06090e'
    - '#4e5a68'
    - '#f0c090'
  brandStrength: 0.6875
  lightness: 0.6875
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
